version: "3"

services:
  dev_comida_justa:
    container_name: devComidaJusta
    build:
      context: ./
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - redComidaJusta
networks:
  redComidaJusta:
    external: true
